updated readme
OperationCode/operationcode-pybot pull request #237
Opened 2020-10-13 11:36 UTC by Vaishnavi-cyber-blip

Added link of latest article in stack bot learning.

2020-10-19 22:14 UTC, aaron-suarez requested changes
Your link is broken, first of all. Second of all, I don't know that I understand what's wrong with the first article that the new article fixes?

If anything, I think we should link to both

2020-10-22 14:31 UTC, Vaishnavi-cyber-blip commented
Till 'create slack app' step everything was okay.
Then we get dashboard to set permission. There is no 'bot user' button (Although they directed very properly if we go on 'where is bot user') . Then comes a dashboard to setup a scope. Then Oauth permission..and then we get access token.

As a beginner when I was following the article to create  setup, I faced little difficulty to understand the changes that lead to the same path.

2020-10-22 15:05 UTC, aaron-suarez commented
Ok well, please fix the link and then we can merge it. It should be

```
[Slack Bot Tutorial](https://www.digitalocean.com/community/tutorials/how-to-build-a-slackbot-in-python-on-ubuntu-20-04)
```

2020-10-22 22:43 UTC, aaron-suarez approved these changes

2020-10-22 22:43 UTC, merged